//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JurisprudenceFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JurisprudenceDBEntities : DbContext
    {
        public JurisprudenceDBEntities()
            : base("name=JurisprudenceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Case> tbl_Case { get; set; }
        public DbSet<tbl_Lawyer> tbl_Lawyer { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
    }
}
