//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JurisprudenceFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Case
    {
        public int CaseID { get; set; }
        public string CaseName { get; set; }
        public string Lawyer { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CaseType { get; set; }
        public string CaseDetails { get; set; }
        public Nullable<bool> Solved { get; set; }
    }
}
