//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JurisprudenceFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lawyer
    {
        public int LawyerID { get; set; }
        public string Name { get; set; }
        public string Degree { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<int> CasesSolved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Specialty { get; set; }
        public string DateJoined { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
